name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: master
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Test command
        run: cat HELP.md

